"""Configuration file for the Sphinx documentation builder.

This file only contains a selection of the most common options. For a full
list see the documentation:
https://www.sphinx-doc.org/en/master/usage/configuration.html
"""
import sys
from pathlib import Path

import sphinx_theme_pd


# -- Path setup --------------------------------------------------------------
# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use the absolute path specification.
#
sys.path.insert(0, Path("..").resolve().absolute())


# -- Project-level information -----------------------------------------------
project = "Hypermodern Python"
author = "Antonio M. Ferreira, Ph.D."
copyright = "2024, Antonio M. Ferreira, Ph.D."


# -- General configuration ---------------------------------------------------
# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx.ext.todo",
    "sphinx.ext.intersphinx",
    "myst_parser",
]

# The master toctree document.
root_doc = "index"

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output
#
# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = "sphinx_theme_pd"
html_theme_path = [sphinx_theme_pd.get_html_theme_path()]

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# A shorter title for the navigation bar.  Default is the same as html_title.
html_short_title = "Hypermodern Python"

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = "_static/logo.png"


# -- Extension configuration -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration
#
autodoc_default_options = {
    "members": True,
    "undoc-members": True,
    "private-members": True,
    "special-members": True,
    "inherited-members": True,
    "show-inheritance": True,
    # 'exclude-members': '__weakref__'
}
autosummary_generate = True
source_suffix = {".rst": "restructuredtext", ".md": "markdown"}
# source_parsers = {'.md': 'recommonmark.parser.CommonMarkParser'}
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store", "**/tests"]
include_patterns = ["_source"]
epub_show_urls = "footnote"

# Suppress specific warnings
suppress_warnings = [
    "autodoc",  # Suppress autodoc warnings
    "duplicate.object.description",  # Suppress duplicate object description warnings
]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

autodoc_typehints = "description"
build_dir = "_build"

# -- Options for todo extension ----------------------------------------------
# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True


# -- Options for LaTeX output ---------------------------------------------
latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    # 'preamble': '',
    # Latex figure (float) alignment
    # 'figure_align': 'htbp',
}

# The name of an image file (relative to this directory) to place at the top of
# the title page.
latex_logo = "_static/logo.png"

# If true, show page references after internal links.
latex_show_pagerefs = True

# If true, show URL addresses after external links.
# latex_show_urls = False

# Documents to append as an appendix to all manuals.
# latex_appendices = []

# If false, no module index is generated.
# latex_domain_indices = True


# -- Options for PDF output --------------------------------------------------
# Place options for generating PDF document here.  For example:
#
#         simplepdf_vars = {
#             "primary_opaque": "rgba(4, 116, 147, 1.0)",
#             "secondary": "rgba(224, 68, 29, 1.0)",
#             "links": "rgba(204, 85, 0, 1.0))",
#             "cover": "rgba(255, 255, 255, .60)",
#             "cover-overlay": "rgba(12, 47, 147, 0.45)",
#             "cover-bg": "url(../../../images/WaveBreak.png) no-repeat center",
#         }
#
