version: "2.0"

# Safety Security and License Configuration file
security:
  # A severity number between 0 and 10.
  # Some helpful reference points: 9=ignore all vulnerabilities except CRITICAL severity.
  # 7=ignore all vulnerabilities except CRITICAL
  ignore-cvss-severity-below: 0

  ignore-cvss-unknown-severity: False # True or False. We recommend you set this to False.
  ignore-vulnerabilities:
    70612:
      reason: Unavoidable for chemistry packages
      expires: "2025-06-01"

  # Suppress non-zero exit codes when vulnerabilities are found. Enable this in pipelines and CI/CD processes
  # if you want to pass builds that have vulnerabilities
  continue-on-vulnerability-error: True
